# Generated by Django 6.0 on 2025-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bio", "0002_personclick"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="death_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="occupation",
            field=models.CharField(
                blank=True,
                help_text="쉼표로 구분된 직업 목록 (예: 코미디언,방송인,유튜버)",
                max_length=500,
                null=True,
            ),
        ),
    ]
