# Generated by Django 6.0 on 2025-12-18 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bio", "0003_person_birth_date_person_death_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("link", "링크"),
                            ("image", "이미지"),
                            ("video", "영상"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text_content", models.TextField(blank=True, null=True)),
                ("link_url", models.URLField(blank=True, null=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="evidences/images/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="evidences/videos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "life_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="bio.lifeevent",
                    ),
                ),
            ],
        ),
    ]
