# Generated by Django 6.0 on 2025-12-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bio", "0004_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="chat_enabled",
            field=models.BooleanField(default=False, help_text="대화 기능 사용 여부"),
        ),
    ]
